name: Natalie Klinke
favicon: null
layout_spectrum: 0.2504648109897971
typography_spectrum: 0.24881
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#90a1b1'
    - '#3d847c'
    - '#93c6c1'
    - '#f1e8d7'
    - '#191c2d'
  brandStrength: 0.9059924308676273
  lightness: 0.37909972248598933
  saturation: 0.35240602120757103
  rhythmicContrast: 0.5425855845678598
purpose: []
